version: '3'
services:
  postgres:
    image: postgres:15-alpine
    container_name: pony-postgres
    networks:
      - network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=${POSTGRES_DB:?}
      - PGDATA=${PGDATA:?}
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    container_name: pony-server
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - network

  client-web:
    build:
      context: .
      dockerfile: client-web/Dockerfile
    restart: unless-stopped
    container_name: pony-client-web
    ports:
      - "3000:3000"
    env_file:
      - client-web/.env
    networks:
      - network

networks:
  network:
    driver: bridge